- Dockerfile
remove using rbenv and use the ruby script in (openstudio-server)[https://raw.githubusercontent.com/NREL/OpenStudio-server/develop/docker/deployment/scripts/install_ruby.sh].
Also add libwxgtk3.0-0 for use openstudio packages newer than 2.4.3.
> use ruby install script from openstudio-server

- README.md
- deploy_docker.sh
Need to merge develop down to master in order for 2.6.1 builds to be updated. The update is needed to support OpenStudio Server's OS_BUNDLE_VERSION variable.
> Update 2.6.1 Build

- .travis.yml
initial openstudio 2.8.0 release
> initial openstudio 2.8.0 release

- .travis.yml
Updating to OpenStudio 2.8.1-rc2
> Updating to 2.8.1 rc2

- .travis.yml
> updatingt to latest sha for rc2

- .travis.yml
- CHANGELOG.md
updating to OpenStudio 2.9.0 rc1
> updating to OpenStudio 2.9.0 rc1

- .travis.yml
- CHANGELOG.md
- README.md
Updating to OpenStudio 2.9.0-rc1
> Updating to OpenStudio 2.9.0-rc1

- .travis.yml
> updating sha for 2.9.0 rc1

- .travis.yml
Updating sha for OpenStudio 2.9.0
> Updating sha for OpenStudio 2.9.0

- .travis.yml
Updating for OpenStudio 2.9.0-rc2
> Updating for OpenStudio 2.9.0-rc2

- .travis.yml
> Updating for 2.9.0 rc3

- .travis.yml
> updated sha for 2.9.0 rc3

- .travis.yml
updating to 2.9.0 official release
> updating to 2.9.0 official release

- .travis.yml
- Dockerfile
Updating for pre-release v.3.0 rc1
> updating for 3.0.0-rc1 pre-release

- .travis.yml
- Dockerfile
- deploy_docker.sh
updating for v3.0.0-pre1 release
> updating for v3.0.0-pre1 release

- .travis.yml
> bumping to v2.9.1-rc1

- .travis.yml
> Updating to v2.9.1-rc1

- .travis.yml
> updating to 2.9.1 official

- .travis.yml
> updating to v2.9.1 official 

- .travis.yml
- Dockerfile
- deploy_docker.sh
Updating for 3.0 beta for OpenStudio incremental build. This has the pycall embedded gem.
> updating for 3.0-beta

- .travis.yml
- Dockerfile
- deploy_docker.sh
Updating for OpenStudio SDK 3.0.0-rc1 release.
>  OpenStudio SDK 3.0.0-rc1

- Dockerfile
update the sha for rc1 on .deb package
> update the sha for rc1 on .deb package

- Dockerfile
> Updating for 3.0.0-rc2

- .travis.yml
- Dockerfile
Updating docker image to v3.0.0-rc3
> update to v3.0.0-rc3

- .travis.yml
- Dockerfile
Updating to official v3.0.0 SDK
> Update to official v3.0.0

- .travis.yml
- Dockerfile
Updating to OpenStudio 3.0.1-rc1
> Updated to 3.0.1-rc1

- .travis.yml
- Dockerfile
Updating OpenStudio to 3.0.1-rc1
> Updating OpenStudio to 3.0.1-rc1

- .travis.yml
- Dockerfile
Updating to OpenStudio 3.0.1-rc2
> updating to OpenStudio 3.0.1-rc2

- Dockerfile
> Update the 3.0.1-rc2 SHA

- .travis.yml
- Dockerfile
> Updating 3.0.1-rc2 SHA

- .travis.yml
- Dockerfile
> Update to 3.0.1

- .travis.yml
- Dockerfile
> Update to v3.0.1

- .travis.yml
- Dockerfile
Updating to OpenStudio 3.1.0-rc1
> Update to 3.1.0-rc1

- .travis.yml
- Dockerfile
> Update deb to use 3.1.0-rc2

- .travis.yml
- Dockerfile
> Updating to 3.1.0-rc2

- .travis.yml
- Dockerfile
Update to OpenStudio 3.1.0-rc3
> Update to OpenStudio 3.1.0-rc3

- .travis.yml
- Dockerfile
> Updating to 3.1.0-rc3

- .travis.yml
- Dockerfile
> Update to 3.1.0-rc4

- .travis.yml
- Dockerfile
Update to OpenStudio v3.1.0-rc4
> Update to OpenStudio v3.1.0-rc4

- .travis.yml
- Dockerfile
> Update to sha 3.1.0-rc4

- .travis.yml
- Dockerfile
> Update to OpenStudio 3.1.0

- .travis.yml
- Dockerfile
> Update OpenStudio to 3.1.0

- .travis.yml
- Dockerfile
> Update to 3.2.0-alpha

- .travis.yml
- Dockerfile
Update to latest available installer for 3.2.0 testing.
> Update installer for 3.2.0-alpha 412729e894

- .travis.yml
- Dockerfile
> update to 3.2.0-rc1

- .travis.yml
- Dockerfile
Updating to official OpenStudio SDK 3.2.0
> update to OpenStudio SDK 3.2.0

- .travis.yml
- Dockerfile
> Update to OpenStudio v3.2.0

- .github/workflows/docker-openstudio.yml
- Dockerfile
> Update to 3.2.1 SDK

- .github/workflows/docker-openstudio.yml
- Dockerfile
> Update to 3.3.0-rc1

- .github/workflows/docker-openstudio.yml
- .github/workflows/manual_installer_test.yml
- Dockerfile
Update to official OS SDK v3.3.0
> Update to official OS SDK v3.3.0

- .github/workflows/docker-openstudio.yml
- .github/workflows/manual_installer_test.yml
- Dockerfile
> Update to OS SDK v3.3.0

- Dockerfile
https://github.com/NREL/docker-openstudio/issues/120
> bump base to 20.04

- .github/workflows/docker-openstudio.yml
- CHANGELOG.md
- Dockerfile
Updates for OpenStudio v3.5.0-rc1
> updates for 3.5.0-rc1

- .github/workflows/docker-openstudio.yml
- Dockerfile
> update to 3.5.0-rc2

- .github/workflows/docker-openstudio.yml
- Dockerfile
- test/test_gemfile.sh
> Bump to 3.7.0 rc2

- deploy_docker.sh
Update the image tag for release
> Rename the docker image tag and friendly remind

- Dockerfile
Used to fix the issue: https://github.com/NREL/docker-openstudio/issues/188
> Cleanup cache
